---
title: "Lab 00 - Hello IDS!"
author: "Lizzy"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

### Exercises 16-17

We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("Lizzy", "Ilayda", "Pari", 
           "Bella", "Serena", "Joyce"),
  github_username = c("lizzyG888", "ilayda639", "ps-18-6", 
                      "isabella-lam", "SerenaT-0729", "yueningYin"), 
  colour = c("purple", "navy", "pink", 
             "pink", "blue","yellow"),
  hobby = c("gaming", "reading", "watching TV", 
            "piano", "drawing", "dancing"),
  favourite_number = c(2, 7, 9, 5, 2,8)
  )

team_data
```

### Exercise 18

We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```

*Remove this text (including the stars), and add your answer for Exercise 18 here.*

